### ISSUE TITLE
老哥能否加个微信bai7426，请教下这个爬虫

### ISSUE THREAD

**Issue by baifengbai** [MatthewTsan/qichachaCrawler#1]

**Comment by MatthewTsan** [comment]
抱歉微信不是很方便，有什么问题我可以在这里回复你的，谢谢你喜欢我的代码

**Comment by baifengbai** [comment]
无论输入是公司还是创始人，都是无法解析页面的关键词，没哟其他报错，是不是需要vip账户的cookie

**Comment by MatthewTsan** [comment]
他们的网站会经常更新，所以解析页面的部分需要修改。
另外需要登陆账户的cookie复制进去的，没有Vip的话只能抓取一部分内容，具体的操作你可以看一下ReadMe。

The HTML structure will be modified regularly, thus you need to update the analysis module in case you are not able to download data.
Before your start the program, remind that you need to log in the website and copy the cookie. For the detail steps, please read the ReadMe.
